### PR TITLE
Add HMS API Secrets

### PR DESCRIPTION
**Pull request by markWarr**

### CODE REVIEW

**Review by maysakanoni — COMMENTED** [review]
`COSMOS_COMMUNAL_STAGING_CONTAINER_ID`
`COSMOS_COMMUNAL_PRODUCTION_CONTAINER_ID`
`COSMOS_LEASEHOLD_STAGING_CONTAINER_ID` 
`COSMOS_LEASEHOLD_PRODUCTION_CONTAINER_ID`
`ANCM_ADDITIONAL_ERROR_PAGE_LINK_PRODUCTION`
`ANCM_ADDITIONAL_ERROR_PAGE_LINK_STAGING`

these are missing, the last two might be generated on deploy but do we need the other 4?

**Comment by markWarr** [comment]
@maysakanoni I've added the first 4 and I've seen that the other 2 are used - they are passed to the app settings in app_service.tf so I've added 
```
ANCM_ADDITIONAL_ERROR_PAGE_LINK_PRODUCTION
ANCM_ADDITIONAL_ERROR_PAGE_LINK_STAGING
```

too.

**Comment by markWarr** [comment]
From @Bhavesh-Patel 
Given the work has been done to provide it via Terraform and therefore is required to be setup as a GitHub secret, if needs to the lightly documented (i.e. set the value to the correct path).

I will create a tech debt ticket to remove this from Github Secrets in the future.

**Review by maysakanoni — APPROVED** [review]

**Comment by markWarr** [comment]
Added tech debt ticket: https://trello.com/c/aoisdE42/344-remove-redundant-secrets-from-hms-api

**Pull request merged**
